### ISSUE TITLE
Timing: report correct unit

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/lighthouse-docker#24]
We're sending `server-response-time` to datadog as seconds when it's actually in milliseconds.

**Comment by ardelato** [comment]
Fixed: 

![image](https://github.com/iFixit/lighthouse-docker/assets/22064420/8745a568-5d1c-47d9-ac85-b4cd3feed849)

![image](https://github.com/iFixit/lighthouse-docker/assets/22064420/4ba40394-9dea-4d29-acb7-b6e757352d7b)
